### ISSUE TITLE
res.write return value is wrong

### ISSUE THREAD

**Issue by phil-mitchell** [gustavnikolaj/hijackresponse#14]
Writable.write returns a boolean.  The overridden res.write returns undefined.  This breaks streamed responses that need to respond to back-pressure from the stream.

**Comment by gustavnikolaj** [comment]
Sorry about the late reply. I've been on vacation and busy getting back to work :-)

I landed a "fix" in the commit above, but failed to run the tests before pushing. We have a test with the compression middleware that starts failing because of this change.

We had support for back pressure through the hijacked response previously, but it seems to be have been removed after finding this problem with the compression middleware.

**Comment by gustavnikolaj** [comment]
Oh, found the missing context :-) https://github.com/gustavnikolaj/hijackresponse/issues/10

I will take a look at the compression middleware and see if I can find a way to fix it.

**Comment by gustavnikolaj** [comment]
Sorry for the flapping - I had to revert the commit again and revert the revert on a feature branch :)

**Comment by gustavnikolaj** [comment]
This should now finally be addressed by the latest release: 5.0.0-rc.1
