### ISSUE TITLE
Release 5.0.0

### ISSUE THREAD

**Issue by gustavnikolaj** [gustavnikolaj/hijackresponse#31]
I've solved all the issues that got added under the [v5 milestone](https://github.com/gustavnikolaj/hijackresponse/milestone/1).

I have released a new RC - 5.0.0-rc.2

I have updated the PRs to use that instead:

- https://github.com/papandreou/express-extractheaders/pull/40
- https://github.com/papandreou/express-compiless/pull/46
- https://github.com/papandreou/express-processimage/pull/120

From my perspective I'm ready to release the major version now, but I'd like a quick sanity check.

@papandreou @alexjeffburke Is there anything I have forgotten about, or which I should do while I am at it?

**Comment by gustavnikolaj** [comment]
Found one thing! The README! 😅  (https://github.com/gustavnikolaj/hijackresponse/issues/32)

**Comment by gustavnikolaj** [comment]
And a migration guide... https://github.com/gustavnikolaj/hijackresponse/issues/33

**Comment by alexjeffburke** [comment]
@gustavnikolaj I've looked over the changes and I certainly think that the post -rc1 cleanups have really made this turn the corner.. nice work!

Couple of small post-release niceties to consider since you're going through the package so thoroughly - one thing I've dropped into many of mine recently is offline-github-changelog, works _really_ nicely with the version hook these days. And I'd also plug `evaldown` at some point for documentation related giggles :)

**Comment by gustavnikolaj** [comment]
@alexjeffburke  Thanks for the suggestion on offline-github-changelog. Added it here: https://github.com/gustavnikolaj/hijackresponse/commit/94a197ff519d933ae5fa01916e33785d93ab98cf

I don't think I'll jump on evaldown just yet 👯  The README has to do for docs now. It's a feature that people has to read the source code to use a module like this ;-)

**Comment by gustavnikolaj** [comment]
Released as 5.0.0 https://github.com/gustavnikolaj/hijackresponse/commit/5affeb3cbd2cdcc0a0981fed5609a7dd227dba2b
